name: Conquista
main: Lop\Main
api: 3.0.1
version: 1
author: lopiin
commands:
  con:
    description: Abrir o menu da conquista (@lopiindev)
  open:
    description: Abrir o menu da caixa (@lopiindev)